npm run typeorm:create migrationName
npm run typeorm:run

////////////////////
//Autogenerated code for migration


export class freeToolCount1682491816318 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {

        if (
            !(await queryRunner.hasColumn('profile', 'freeToolCount')) //'profile' is the table where 'freeToolCount' is createds
          ) {
            await queryRunner.addColumn(
              'profile',			//same name as above
              new TableColumn({
                name: 'freeToolCount',		//same name as above
                type: 'integer',
                default: 0
              }),
            );
          }    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.rollbackTransaction()
    }

}
