npm run typeorm:create migrationName
npm run typeorm:run

////////////////////
//Autogenerated code for migration


export class freeToolCount1682491816318 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {

        if (
            !(await queryRunner.hasColumn('profile', 'freeToolCount')) //'profile' is the table where 'freeToolCount' is createds
          ) {
            await queryRunner.addColumn(
              'profile',			//same name as above
              new TableColumn({
                name: 'freeToolCount',		//same name as above
                type: 'integer',
                default: 0
              }),
            );
          }    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.rollbackTransaction()
    }

}

        
-----------------------------------------------------------------APPLIED CODE----------------------------------------------------------------------------
        
        import {MigrationInterface, QueryRunner, TableColumn} from "typeorm";

export class UpdateProfileTable1683803983836 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {


        if (!(await queryRunner.hasColumn('profile', 'userCode'))) {
            await queryRunner.addColumn('profile', new TableColumn({
                name: 'userCode',
                type: 'string',
                default: null
              }),
            );
          }


          if (!(await queryRunner.hasColumn('profile', 'referralCode'))) {
            await queryRunner.addColumn('profile', new TableColumn({
                name: 'referralCode',
                type: 'string',
                default: null
              }),
            );
          }

        }
    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.rollbackTransaction()
    }

}
